from decimal import Decimal

from sqlalchemy import (
    Date,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
    func,
)
from sqlalchemy.orm import (
    Mapped,
    mapped_column,
)

from app.database.base import Base


class FinancialYear(Base):
    __tablename__ = "financial_years"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    # Example:
    # 2026-2027
    name: Mapped[str] = mapped_column(
        String(20),
        nullable=False,
        unique=True,
        index=True,
    )

    start_date: Mapped[
        object
    ] = mapped_column(
        Date,
        nullable=False,
        unique=True,
        index=True,
    )

    end_date: Mapped[
        object
    ] = mapped_column(
        Date,
        nullable=False,
        unique=True,
        index=True,
    )

    # ACTIVE
    # CLOSED
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        default="ACTIVE",
        server_default="ACTIVE",
        index=True,
    )

    opened_at: Mapped[
        object
    ] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    opened_by: Mapped[
        int | None
    ] = mapped_column(
        ForeignKey(
            "users.id",
            ondelete="SET NULL",
        ),
        nullable=True,
    )

    closed_at: Mapped[
        object | None
    ] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    closed_by: Mapped[
        int | None
    ] = mapped_column(
        ForeignKey(
            "users.id",
            ondelete="SET NULL",
        ),
        nullable=True,
    )

    notes: Mapped[
        str | None
    ] = mapped_column(
        Text,
        nullable=True,
    )

    created_at: Mapped[
        object
    ] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    updated_at: Mapped[
        object
    ] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        onupdate=func.now(),
        nullable=False,
    )


class FinancialYearTransitionLog(Base):
    __tablename__ = "financial_year_transition_logs"

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    from_financial_year_id: Mapped[
        int
    ] = mapped_column(
        ForeignKey(
            "financial_years.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    to_financial_year_id: Mapped[
        int | None
    ] = mapped_column(
        ForeignKey(
            "financial_years.id",
            ondelete="RESTRICT",
        ),
        nullable=True,
        index=True,
    )

    backup_log_id: Mapped[
        int | None
    ] = mapped_column(
        ForeignKey(
            "backup_logs.id",
            ondelete="SET NULL",
        ),
        nullable=True,
        index=True,
    )

    # VALIDATING
    # READY
    # RUNNING
    # COMPLETED
    # FAILED
    status: Mapped[str] = mapped_column(
        String(30),
        nullable=False,
        index=True,
    )

    # JSON text generated by the transition service.
    validation_summary: Mapped[
        str | None
    ] = mapped_column(
        Text,
        nullable=True,
    )

    carry_forward_summary: Mapped[
        str | None
    ] = mapped_column(
        Text,
        nullable=True,
    )

    started_by: Mapped[int] = mapped_column(
        ForeignKey(
            "users.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    started_at: Mapped[
        object
    ] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )

    completed_at: Mapped[
        object | None
    ] = mapped_column(
        DateTime(timezone=True),
        nullable=True,
    )

    error_message: Mapped[
        str | None
    ] = mapped_column(
        Text,
        nullable=True,
    )


class FinancialYearOpeningStock(Base):
    __tablename__ = "financial_year_opening_stock"

    __table_args__ = (
        UniqueConstraint(
            "financial_year_id",
            "product_id",
            name=(
                "uq_financial_year_"
                "opening_stock_product"
            ),
        ),
    )

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    financial_year_id: Mapped[int] = mapped_column(
        ForeignKey(
            "financial_years.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    product_id: Mapped[int] = mapped_column(
        ForeignKey(
            "products.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    opening_quantity: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    unit_cost: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    opening_value: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(16, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    source_closing_date: Mapped[
        object
    ] = mapped_column(
        Date,
        nullable=False,
    )

    created_at: Mapped[
        object
    ] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )


class FinancialYearOpeningWIP(Base):
    __tablename__ = "financial_year_opening_wip"

    __table_args__ = (
        UniqueConstraint(
            "financial_year_id",
            "production_order_id",
            name=(
                "uq_financial_year_"
                "opening_wip_production"
            ),
        ),
    )

    id: Mapped[int] = mapped_column(
        Integer,
        primary_key=True,
        index=True,
    )

    financial_year_id: Mapped[int] = mapped_column(
        ForeignKey(
            "financial_years.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    production_order_id: Mapped[
        int
    ] = mapped_column(
        ForeignKey(
            "production_orders.id",
            ondelete="RESTRICT",
        ),
        nullable=False,
        index=True,
    )

    material_cost: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    operation_cost: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    direct_expense_cost: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    allocated_staff_cost: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    allocated_overhead_cost: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(14, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    total_opening_wip: Mapped[
        Decimal
    ] = mapped_column(
        Numeric(16, 2),
        nullable=False,
        default=Decimal("0.00"),
        server_default="0.00",
    )

    source_closing_date: Mapped[
        object
    ] = mapped_column(
        Date,
        nullable=False,
    )

    created_at: Mapped[
        object
    ] = mapped_column(
        DateTime(timezone=True),
        server_default=func.now(),
        nullable=False,
    )