from sqlalchemy.orm import Session

from app.models.final_bill import FinalBill
from app.models.finished_goods_receipt import (
    FinishedGoodsReceipt,
)
from app.models.finished_product import (
    FinishedProduct,
)
from app.models.production_order import (
    ProductionOrder,
)
from app.models.proforma import (
    Proforma,
)


class ProductionReopenService:

    # ============================================================
    # REOPEN COMPLETED PRODUCTION
    # ============================================================

    @staticmethod
    def reopen(
        db: Session,
        production_order_id: int,
    ) -> ProductionOrder:

        """
        Boss-only recovery workflow.

        Reopening a completed Production Order:

        - is allowed only while no Final Bill exists
          for the linked Proforma
        - deletes the Finished Product generated by completion
        - deletes the Finished Goods Receipt generated by completion
        - returns Production Order to In Progress
        - clears Actual End date
        - returns Proforma to Production Started
        - preserves issued materials
        - preserves Production Operations

        Everything is performed in one database transaction.
        """

        try:

            # ====================================================
            # LOCK PRODUCTION ORDER
            # ====================================================

            production_order = (
                db.query(
                    ProductionOrder
                )
                .filter(
                    ProductionOrder.id
                    == production_order_id
                )
                .with_for_update()
                .first()
            )


            if (
                production_order
                is None
            ):

                raise LookupError(
                    "Production Order not found."
                )


            production_status = (
                production_order.status
                or ""
            ).strip().lower()


            if (
                production_status
                != "completed"
            ):

                raise ValueError(
                    "Only a Completed Production Order "
                    "can be reopened."
                )


            # ====================================================
            # BLOCK AFTER FINAL BILL CREATION
            #
            # Even a Draft Final Bill means billing has already
            # started, so Production must not be silently reversed.
            # ====================================================

            existing_final_bill = (
                db.query(
                    FinalBill
                )
                .filter(
                    FinalBill.proforma_id
                    == production_order.proforma_id
                )
                .first()
            )


            if (
                existing_final_bill
                is not None
            ):

                raise ValueError(
                    "Production cannot be reopened because "
                    "Final Billing has already started for this "
                    "Proforma. Existing Final Bill: "
                    f"{existing_final_bill.invoice_number}."
                )


            # ====================================================
            # LOCK COMPLETION RECORDS
            # ====================================================

            finished_product = (
                db.query(
                    FinishedProduct
                )
                .filter(
                    FinishedProduct.production_order_id
                    == production_order.id
                )
                .with_for_update()
                .first()
            )


            finished_goods_receipt = (
                db.query(
                    FinishedGoodsReceipt
                )
                .filter(
                    FinishedGoodsReceipt.production_order_id
                    == production_order.id
                )
                .with_for_update()
                .first()
            )


            # ====================================================
            # REMOVE FINISHED PRODUCT FIRST
            #
            # Finished Product references the Finished Goods
            # Receipt, therefore delete it before deleting FGR.
            # ====================================================

            if (
                finished_product
                is not None
            ):

                db.delete(
                    finished_product
                )

                db.flush()


            # ====================================================
            # REMOVE FINISHED GOODS RECEIPT
            # ====================================================

            if (
                finished_goods_receipt
                is not None
            ):

                db.delete(
                    finished_goods_receipt
                )

                db.flush()


            # ====================================================
            # RESTORE PRODUCTION ORDER
            # ====================================================

            production_order.status = (
                "In Progress"
            )

            production_order.actual_end_date = (
                None
            )


            # ====================================================
            # RESTORE PROFORMA WORKFLOW STATUS
            # ====================================================

            proforma = (
                db.query(
                    Proforma
                )
                .filter(
                    Proforma.id
                    == production_order.proforma_id
                )
                .with_for_update()
                .first()
            )


            if (
                proforma
                is not None
            ):

                proforma.status = (
                    "Production Started"
                )


            # ====================================================
            # IMPORTANT
            #
            # We intentionally DO NOT reverse:
            #
            # - Production Materials
            # - Store issues
            # - Production Operations
            # - actual_start_date
            #
            # Those events genuinely happened and must remain
            # traceable.
            # ====================================================


            db.commit()


            db.refresh(
                production_order
            )


            return production_order


        except Exception:

            db.rollback()

            raise