"""create shop floor issue table

Revision ID: 1492309d4243
Revises: af0bd9562a7a
Create Date: 2026-09-04 11:37:38.405808

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1492309d4243'
down_revision: Union[str, Sequence[str], None] = 'af0bd9562a7a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shop_floor_issues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('issue_number', sa.String(length=30), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('production_material_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_issued', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('issued_by', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['issued_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_material_id'], ['production_materials.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shop_floor_issues_id'), 'shop_floor_issues', ['id'], unique=False)
    op.create_index(op.f('ix_shop_floor_issues_issue_number'), 'shop_floor_issues', ['issue_number'], unique=True)
    op.create_index(op.f('ix_shop_floor_issues_issued_at'), 'shop_floor_issues', ['issued_at'], unique=False)
    op.create_index(op.f('ix_shop_floor_issues_issued_by'), 'shop_floor_issues', ['issued_by'], unique=False)
    op.create_index(op.f('ix_shop_floor_issues_product_id'), 'shop_floor_issues', ['product_id'], unique=False)
    op.create_index(op.f('ix_shop_floor_issues_production_material_id'), 'shop_floor_issues', ['production_material_id'], unique=False)
    op.create_index(op.f('ix_shop_floor_issues_production_order_id'), 'shop_floor_issues', ['production_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shop_floor_issues_production_order_id'), table_name='shop_floor_issues')
    op.drop_index(op.f('ix_shop_floor_issues_production_material_id'), table_name='shop_floor_issues')
    op.drop_index(op.f('ix_shop_floor_issues_product_id'), table_name='shop_floor_issues')
    op.drop_index(op.f('ix_shop_floor_issues_issued_by'), table_name='shop_floor_issues')
    op.drop_index(op.f('ix_shop_floor_issues_issued_at'), table_name='shop_floor_issues')
    op.drop_index(op.f('ix_shop_floor_issues_issue_number'), table_name='shop_floor_issues')
    op.drop_index(op.f('ix_shop_floor_issues_id'), table_name='shop_floor_issues')
    op.drop_table('shop_floor_issues')
    # ### end Alembic commands ###
