"""create finished goods receipt table

Revision ID: 3a74fe979551
Revises: 1492309d4243
Create Date: 2026-09-04 21:33:53.017520

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a74fe979551'
down_revision: Union[str, Sequence[str], None] = '1492309d4243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_goods_receipts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receipt_number', sa.String(length=30), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('quantity_received', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('received_by', sa.Integer(), nullable=False),
    sa.Column('received_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['received_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('production_order_id', name='uq_finished_goods_receipt_production_order')
    )
    op.create_index(op.f('ix_finished_goods_receipts_id'), 'finished_goods_receipts', ['id'], unique=False)
    op.create_index(op.f('ix_finished_goods_receipts_product_id'), 'finished_goods_receipts', ['product_id'], unique=False)
    op.create_index(op.f('ix_finished_goods_receipts_production_order_id'), 'finished_goods_receipts', ['production_order_id'], unique=False)
    op.create_index(op.f('ix_finished_goods_receipts_receipt_number'), 'finished_goods_receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_finished_goods_receipts_received_at'), 'finished_goods_receipts', ['received_at'], unique=False)
    op.create_index(op.f('ix_finished_goods_receipts_received_by'), 'finished_goods_receipts', ['received_by'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finished_goods_receipts_received_by'), table_name='finished_goods_receipts')
    op.drop_index(op.f('ix_finished_goods_receipts_received_at'), table_name='finished_goods_receipts')
    op.drop_index(op.f('ix_finished_goods_receipts_receipt_number'), table_name='finished_goods_receipts')
    op.drop_index(op.f('ix_finished_goods_receipts_production_order_id'), table_name='finished_goods_receipts')
    op.drop_index(op.f('ix_finished_goods_receipts_product_id'), table_name='finished_goods_receipts')
    op.drop_index(op.f('ix_finished_goods_receipts_id'), table_name='finished_goods_receipts')
    op.drop_table('finished_goods_receipts')
    # ### end Alembic commands ###
