"""add purchase bill payment tracking

Revision ID: 49f5016ccf1e
Revises: a570c033cc46
Create Date: 2026-09-17 11:35:29.935134

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '49f5016ccf1e'
down_revision: Union[str, Sequence[str], None] = 'a570c033cc46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('purchase_bill_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_bill_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('payment_mode', sa.String(length=50), nullable=True),
    sa.Column('reference_number', sa.String(length=100), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['purchase_bill_id'], ['purchase_bills.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_purchase_bill_payments_created_by'), 'purchase_bill_payments', ['created_by'], unique=False)
    op.create_index(op.f('ix_purchase_bill_payments_id'), 'purchase_bill_payments', ['id'], unique=False)
    op.create_index(op.f('ix_purchase_bill_payments_payment_date'), 'purchase_bill_payments', ['payment_date'], unique=False)
    op.create_index(op.f('ix_purchase_bill_payments_purchase_bill_id'), 'purchase_bill_payments', ['purchase_bill_id'], unique=False)
    op.add_column('purchase_bills', sa.Column('credit_days', sa.Integer(), server_default='0', nullable=False))
    op.add_column('purchase_bills', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_purchase_bills_due_date'), 'purchase_bills', ['due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_purchase_bills_due_date'), table_name='purchase_bills')
    op.drop_column('purchase_bills', 'due_date')
    op.drop_column('purchase_bills', 'credit_days')
    op.drop_index(op.f('ix_purchase_bill_payments_purchase_bill_id'), table_name='purchase_bill_payments')
    op.drop_index(op.f('ix_purchase_bill_payments_payment_date'), table_name='purchase_bill_payments')
    op.drop_index(op.f('ix_purchase_bill_payments_id'), table_name='purchase_bill_payments')
    op.drop_index(op.f('ix_purchase_bill_payments_created_by'), table_name='purchase_bill_payments')
    op.drop_table('purchase_bill_payments')
    # ### end Alembic commands ###
