"""create final billing tables

Revision ID: 5d54ca296856
Revises: 98a89254e26a
Create Date: 2026-09-05 20:05:29.654247

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5d54ca296856'
down_revision: Union[str, Sequence[str], None] = '98a89254e26a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('final_bills',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('invoice_number', sa.String(length=30), nullable=False),
    sa.Column('invoice_date', sa.Date(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('gst_number', sa.String(length=50), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('invoice_type', sa.String(length=30), nullable=False),
    sa.Column('status', sa.String(length=30), nullable=False),
    sa.Column('revision_number', sa.Integer(), nullable=False),
    sa.Column('parent_invoice_id', sa.Integer(), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['parent_invoice_id'], ['final_bills.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['proforma_id'], ['proformas.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_bills_created_by'), 'final_bills', ['created_by'], unique=False)
    op.create_index(op.f('ix_final_bills_customer_id'), 'final_bills', ['customer_id'], unique=False)
    op.create_index(op.f('ix_final_bills_id'), 'final_bills', ['id'], unique=False)
    op.create_index(op.f('ix_final_bills_invoice_date'), 'final_bills', ['invoice_date'], unique=False)
    op.create_index(op.f('ix_final_bills_invoice_number'), 'final_bills', ['invoice_number'], unique=True)
    op.create_index(op.f('ix_final_bills_invoice_type'), 'final_bills', ['invoice_type'], unique=False)
    op.create_index(op.f('ix_final_bills_parent_invoice_id'), 'final_bills', ['parent_invoice_id'], unique=False)
    op.create_index(op.f('ix_final_bills_proforma_id'), 'final_bills', ['proforma_id'], unique=False)
    op.create_index(op.f('ix_final_bills_status'), 'final_bills', ['status'], unique=False)
    op.create_table('final_bill_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('final_bill_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('unit_price', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('discount_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('discount_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_percent', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('cgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('sgst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('igst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('tax_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['final_bill_id'], ['final_bills.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_final_bill_items_final_bill_id'), 'final_bill_items', ['final_bill_id'], unique=False)
    op.create_index(op.f('ix_final_bill_items_id'), 'final_bill_items', ['id'], unique=False)
    op.create_index(op.f('ix_final_bill_items_product_id'), 'final_bill_items', ['product_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_final_bill_items_product_id'), table_name='final_bill_items')
    op.drop_index(op.f('ix_final_bill_items_id'), table_name='final_bill_items')
    op.drop_index(op.f('ix_final_bill_items_final_bill_id'), table_name='final_bill_items')
    op.drop_table('final_bill_items')
    op.drop_index(op.f('ix_final_bills_status'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_proforma_id'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_parent_invoice_id'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_invoice_type'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_invoice_number'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_invoice_date'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_id'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_customer_id'), table_name='final_bills')
    op.drop_index(op.f('ix_final_bills_created_by'), table_name='final_bills')
    op.drop_table('final_bills')
    # ### end Alembic commands ###
