"""remove obsolete product created_by

Revision ID: 934f16e91004
Revises: 14d2d7738759
Create Date: 2026-09-02 19:36:02.728880

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '934f16e91004'
down_revision: Union[str, Sequence[str], None] = '14d2d7738759'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_products_created_by'), 'products', type_='foreignkey')
    op.drop_column('products', 'created_by')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('created_by', mysql.INTEGER(), server_default=sa.text("'1'"), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('fk_products_created_by'), 'products', 'users', ['created_by'], ['id'])
    # ### end Alembic commands ###
