"""create stock movement ledger

Revision ID: 98a89254e26a
Revises: 3a74fe979551
Create Date: 2026-09-05 13:03:17.905581

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '98a89254e26a'
down_revision: Union[str, Sequence[str], None] = '3a74fe979551'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('stock_movements',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('movement_type', sa.String(length=50), nullable=False),
    sa.Column('source_type', sa.String(length=50), nullable=False),
    sa.Column('source_id', sa.Integer(), nullable=False),
    sa.Column('source_number', sa.String(length=100), nullable=False),
    sa.Column('quantity_in', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('quantity_out', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_before', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('stock_after', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit_cost', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('movement_value', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('performed_by', sa.Integer(), nullable=False),
    sa.Column('movement_date', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.CheckConstraint('(quantity_in > 0 AND quantity_out = 0) OR (quantity_out > 0 AND quantity_in = 0)', name='ck_stock_movement_single_direction'),
    sa.CheckConstraint('movement_value >= 0', name='ck_stock_movement_value_nonnegative'),
    sa.CheckConstraint('quantity_in >= 0', name='ck_stock_movement_quantity_in_nonnegative'),
    sa.CheckConstraint('quantity_out >= 0', name='ck_stock_movement_quantity_out_nonnegative'),
    sa.CheckConstraint('stock_after >= 0', name='ck_stock_movement_stock_after_nonnegative'),
    sa.CheckConstraint('stock_before >= 0', name='ck_stock_movement_stock_before_nonnegative'),
    sa.CheckConstraint('unit_cost >= 0', name='ck_stock_movement_unit_cost_nonnegative'),
    sa.ForeignKeyConstraint(['performed_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('source_type', 'source_id', 'product_id', 'movement_type', name='uq_stock_movement_source_product_type')
    )
    op.create_index(op.f('ix_stock_movements_id'), 'stock_movements', ['id'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_date'), 'stock_movements', ['movement_date'], unique=False)
    op.create_index(op.f('ix_stock_movements_movement_type'), 'stock_movements', ['movement_type'], unique=False)
    op.create_index(op.f('ix_stock_movements_performed_by'), 'stock_movements', ['performed_by'], unique=False)
    op.create_index(op.f('ix_stock_movements_product_id'), 'stock_movements', ['product_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_source_id'), 'stock_movements', ['source_id'], unique=False)
    op.create_index(op.f('ix_stock_movements_source_number'), 'stock_movements', ['source_number'], unique=False)
    op.create_index(op.f('ix_stock_movements_source_type'), 'stock_movements', ['source_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_stock_movements_source_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_source_number'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_source_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_product_id'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_performed_by'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_type'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_movement_date'), table_name='stock_movements')
    op.drop_index(op.f('ix_stock_movements_id'), table_name='stock_movements')
    op.drop_table('stock_movements')
    # ### end Alembic commands ###
