"""create finished product table

Revision ID: a570c033cc46
Revises: 7a4d7df081ef
Create Date: 2026-09-16 16:37:27.237308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a570c033cc46'
down_revision: Union[str, Sequence[str], None] = '7a4d7df081ef'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('finished_products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('finished_product_number', sa.String(length=30), nullable=False),
    sa.Column('product_master_id', sa.Integer(), nullable=False),
    sa.Column('production_order_id', sa.Integer(), nullable=False),
    sa.Column('finished_goods_receipt_id', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['finished_goods_receipt_id'], ['finished_goods_receipts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_master_id'], ['products.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['production_order_id'], ['production_orders.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('finished_goods_receipt_id', name='uq_finished_product_goods_receipt'),
    sa.UniqueConstraint('production_order_id', name='uq_finished_product_production_order')
    )
    op.create_index(op.f('ix_finished_products_created_by'), 'finished_products', ['created_by'], unique=False)
    op.create_index(op.f('ix_finished_products_finished_goods_receipt_id'), 'finished_products', ['finished_goods_receipt_id'], unique=False)
    op.create_index(op.f('ix_finished_products_finished_product_number'), 'finished_products', ['finished_product_number'], unique=True)
    op.create_index(op.f('ix_finished_products_id'), 'finished_products', ['id'], unique=False)
    op.create_index(op.f('ix_finished_products_product_master_id'), 'finished_products', ['product_master_id'], unique=False)
    op.create_index(op.f('ix_finished_products_production_order_id'), 'finished_products', ['production_order_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_finished_products_production_order_id'), table_name='finished_products')
    op.drop_index(op.f('ix_finished_products_product_master_id'), table_name='finished_products')
    op.drop_index(op.f('ix_finished_products_id'), table_name='finished_products')
    op.drop_index(op.f('ix_finished_products_finished_product_number'), table_name='finished_products')
    op.drop_index(op.f('ix_finished_products_finished_goods_receipt_id'), table_name='finished_products')
    op.drop_index(op.f('ix_finished_products_created_by'), table_name='finished_products')
    op.drop_table('finished_products')
    # ### end Alembic commands ###
