"""convert stock quantities to decimal

Revision ID: af0bd9562a7a
Revises: 934f16e91004
Create Date: 2026-09-04 11:19:31.668834

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'af0bd9562a7a'
down_revision: Union[str, Sequence[str], None] = '934f16e91004'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'minimum_stock',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'maximum_stock',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    op.alter_column('products', 'current_stock',
               existing_type=mysql.INTEGER(),
               type_=sa.Numeric(precision=12, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'current_stock',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'maximum_stock',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    op.alter_column('products', 'minimum_stock',
               existing_type=sa.Numeric(precision=12, scale=2),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
