"""add is_active to purchase_bill

Revision ID: b656edf005c4
Revises: 34698ce8cf85
Create Date: 2026-07-19 18:45:30.674091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b656edf005c4'
down_revision: Union[str, Sequence[str], None] = '34698ce8cf85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('purchase_bills', sa.Column('is_active', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('purchase_bills', 'is_active')
    # ### end Alembic commands ###
