"""create proforma tables

Revision ID: beb2a6dca7aa
Revises: create_enquiry_table
Create Date: 2026-08-25 16:43:25.167359

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'beb2a6dca7aa'
down_revision: Union[str, Sequence[str], None] = 'create_enquiry_table'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('proformas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_number', sa.String(length=30), nullable=False),
    sa.Column('proforma_date', sa.Date(), nullable=False),
    sa.Column('enquiry_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('company_name', sa.String(length=200), nullable=False),
    sa.Column('contact_person', sa.String(length=150), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('billing_address', sa.String(length=500), nullable=True),
    sa.Column('shipping_address', sa.String(length=500), nullable=True),
    sa.Column('validity_days', sa.Integer(), nullable=True),
    sa.Column('payment_terms', sa.Text(), nullable=True),
    sa.Column('delivery_terms', sa.Text(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('subtotal', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('grand_total', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['enquiry_id'], ['enquiries.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proformas_customer_id'), 'proformas', ['customer_id'], unique=False)
    op.create_index(op.f('ix_proformas_enquiry_id'), 'proformas', ['enquiry_id'], unique=False)
    op.create_index(op.f('ix_proformas_id'), 'proformas', ['id'], unique=False)
    op.create_index(op.f('ix_proformas_proforma_number'), 'proformas', ['proforma_number'], unique=True)
    op.create_index(op.f('ix_proformas_status'), 'proformas', ['status'], unique=False)
    op.create_table('proforma_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proforma_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('product_name', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hsn_code', sa.String(length=20), nullable=True),
    sa.Column('quantity', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('unit', sa.String(length=30), nullable=True),
    sa.Column('rate', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('taxable_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('gst_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.Column('total_amount', sa.Numeric(precision=14, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['proforma_id'], ['proformas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_proforma_items_id'), 'proforma_items', ['id'], unique=False)
    op.create_index(op.f('ix_proforma_items_product_id'), 'proforma_items', ['product_id'], unique=False)
    op.create_index(op.f('ix_proforma_items_proforma_id'), 'proforma_items', ['proforma_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_proforma_items_proforma_id'), table_name='proforma_items')
    op.drop_index(op.f('ix_proforma_items_product_id'), table_name='proforma_items')
    op.drop_index(op.f('ix_proforma_items_id'), table_name='proforma_items')
    op.drop_table('proforma_items')
    op.drop_index(op.f('ix_proformas_status'), table_name='proformas')
    op.drop_index(op.f('ix_proformas_proforma_number'), table_name='proformas')
    op.drop_index(op.f('ix_proformas_id'), table_name='proformas')
    op.drop_index(op.f('ix_proformas_enquiry_id'), table_name='proformas')
    op.drop_index(op.f('ix_proformas_customer_id'), table_name='proformas')
    op.drop_table('proformas')
    # ### end Alembic commands ###
